//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageRender.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageRender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;svg width=&apos;800&apos; height=&apos;600&apos; xmlns=&apos;http://www.w3.org/2000/svg&apos;&gt;
        /// &lt;defs&gt;&lt;style&gt;.cls-t{fill:#547C36;}.cls-0{fill:rgb(126,238,0); stroke-width:1; stroke:#547C36}.cls-9{fill:#547C36}.cls-1{fill:#e3e3e3;}.cls-2{fill:#f5f5f5;}.cls-3{fill:#b1b1b1;}.a{fill:#fff;stroke:#fff;stroke-miterlimit:10;stroke-width:4px;}.b{fill:#e5e4e4;}.c{fill:#030504;}.d{fill:#f0b600;}.e{fill:#bdbdbd;}.f{fill:#5db998;}.g{fill:#eeb500;}.h{fill:#458a70;}.i{fill:#d9a712;}.j{fill:#5bb998;}.k{fill:#aeaeae;}.l{fill:#fdde82;}.m{fill:#3ebcd4;} [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Template202002 {
            get {
                return ResourceManager.GetString("Template202002", resourceCulture);
            }
        }
    }
}
